

services:
  db-server:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: quan_ly_nha_xe_db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: quan_ly_nha_xe
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 60

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quan_ly_nha_xe_backend
    environment:
      - DB_HOST=db-server
      - DB_PORT=3306
      - DB_USER=root
    ports:
      - "8080:8080"
    depends_on:
      db-server:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quan_ly_nha_xe_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data: