

services:
  db-server:
    image: mysql:8.0
    container_name: db-server
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: quan_ly_nha_xe
    ports:
      - "3308:3306" # Map port 3308 của máy bạn vào 3306 của container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # TỰ ĐỘNG CHẠY FILE SQL KHI TẠO DB

  web-app:
    build: ./backend
    container_name: web-app
    ports:
      - "8080:8080"
    depends_on:
      - db-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-server:3306/quan_ly_nha_xe?allowPublicKeyRetrieval=true&useSSL=false

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173" # Hoặc 3000 tùy cấu hình
    depends_on:
      - web-app

volumes:
  mysql_data: