spring.application.name=backend
server.port=8080

# Đổi localhost thành db-server (tên container mysql của bạn) và port thành 3306
spring.datasource.url=jdbc:mysql://db-server:3306/quan_ly_nha_xe?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.initialization-fail-timeout=0